### PR TITLE
:bug: Reset wizard form after analysis run

### LINKED ISSUE #1256: Sometimes wizard state is persisted between analysis runs
I think that we need to refactor the analysis wizard to use our new modal paradigm. Seems that there is an intermittent bug involving multiple modals with separate state that isn't being cleaned up.

### PR DESCRIPTION
**Pull request by ibolton336**
- Resolves #1256 
- When closing the wizard, the taskgroup state hangs around between analysis runs causing problems. This PR cleans up the react state when closing/submitting the analysis wizard

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]
although would it make sense to call `handleClose` here? does both `reset()` and `onClose()`, i'm unsure about the delete task group stuff though.

**Comment by ibolton336** [comment]
> although would it make sense to call `handleClose` here? does both `reset()` and `onClose()`, i'm unsure about the delete task group stuff though.

You're right on the money. Our delete task group stuff was very wrong and needs to be refactored.

**Comment by ibolton336** [comment]
@gitdallas Updated - good idea to consolidate that logic.

File: client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx [hunk 1]
```diff
@@ -286,28 +280,37 @@ export const AnalysisWizard: React.FC<IAnalysisWizard> = ({
...
-    onClose();
+    resetWizard();
   };
 
   const onMove: WizardStepFunctionType = (
     { id, name },
     { prevId, prevName }
   ) => {
     if (id && stepIdReached < (id as number)) setStepIdReached(id as number);
+    if (id === 2) {
```
Comment (gitdallas) [inline client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx:302]: What is 2? Any way we can use a step property or something instead?

Line 301 indicates that id is a string (otherwise why `as number`?), but line 302 is treating it as a number.

Comment (ibolton336) [reply client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx:302]: Good point - we used to have an enum for this. I will create another one.

Comment (ibolton336) [reply client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx:302]: Screenshot 2023-08-08 at 2 54 07 PM
Looks like the string/number type is coming from PF.

File: client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx [hunk 2]
```diff
@@ -84,7 +84,10 @@ export const ApplicationsTableAnalyze: React.FC = () => {
   const { t } = useTranslation();
   const { pushNotification } = React.useContext(NotificationsContext);
 
-  const [isAnalyzeModalOpen, setAnalyzeModalOpen] = React.useState(false);
+  const [createUpdateModalState, setCreateUpdateModalState] = React.useState<
+    Application | Application[] | null
+  >(null);
```
Comment (gildub) [inline client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx:89]: The default value should be empty array `[]` and the null type is not needed.

File: client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx [hunk 3]
```diff
@@ -84,7 +84,10 @@ export const ApplicationsTableAnalyze: React.FC = () => {
...
+  const isWizardOpen = createUpdateModalState !== null;
```
Comment (gildub) [inline client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx:90]:
```suggestion
  const isWizardOpen = createUpdateModalState.length > 0;
```

File: client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx [hunk 4]
```diff
@@ -613,9 +616,9 @@ export const ApplicationsTableAnalyze: React.FC = () => {
       </Modal>{" "}
       <AnalysisWizard
         applications={selectedRows}
-        isOpen={isAnalyzeModalOpen}
+        isOpen={isWizardOpen}
         onClose={() => {
-          setAnalyzeModalOpen(false);
+          setCreateUpdateModalState(null);
```
Comment (gildub) [inline client/src/app/pages/applications/applications-table-analyze/applications-table-analyze.tsx:621]:
```suggestion
          setCreateUpdateModalState([]);
```

File: client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx [hunk 5]
```diff
@@ -286,28 +280,37 @@ export const AnalysisWizard: React.FC<IAnalysisWizard> = ({
   };
 
   const isModeValid = applications.every((app) => isModeSupported(app, mode));
+  const resetWizard = () => {
+    setCurrentTaskgroup(null);
+    reset();
+    onClose();
```
Comment (gildub) [inline client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx:286]: Why close the wizard here ?

**Review by gildub — COMMENTED** [review]
Please see inline.

File: client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx [hunk 6]
```diff
@@ -286,28 +280,37 @@ export const AnalysisWizard: React.FC<IAnalysisWizard> = ({
   };
 
   const isModeValid = applications.every((app) => isModeSupported(app, mode));
+  const resetWizard = () => {
```
[the remark this answers is not in the document]
Comment (gitdallas) [reply client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx:283]: @ibolton336  - actually the `delete` is more of a cancel right? maybe just `handleCancel` which could delete and then call the close function

[the remark this answers is not in the document]
Comment (ibolton336) [reply client/src/app/pages/applications/analysis-wizard/analysis-wizard.tsx]: Updated.

**Review by gitdallas — APPROVED** [review]
