### PR TITLE
:bug: Always show analysis details in drawer

### LINKED ISSUE #1013: Don't show drawer spinner for ongoing analysis run
We should be able to view analysis report details while the analysis is running. We should link to app details like we currently do in the kebab menu for analysis details.

### LINKED ISSUE #1100: Facts tab shows when no facts are present in the app drawer

### PR DESCRIPTION
**Pull request by ibolton336**
- It was reported (no bz) that the analysis details should always be accessible from the side drawer. This PR removes the spinner for in-progress analysis status & replaces it with a link to the code viewer modal. Resolves #1013 
- Also, this PR hides the facts tab when no facts are present. Resolves #1100

### CODE REVIEW

**Comment by ibolton336** [comment]
Screenshot 2023-07-10 at 12 24 23 PM

File: client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx [hunk 1]
```diff
@@ -134,25 +131,50 @@ export const ApplicationDetailDrawerAnalysis: React.FC<
...
+                  variant="link"
+                  onClick={() => setTaskIdToView(task?.id)}
+                  className={spacing.ml_0}
+                  style={{ margin: "0", padding: "0" }}
+                >
+                  Analysis details
+                </Button>
+              ) : null}
+
+              {notAvailable}
```
Comment (mturley) [inline client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx:164]: This `notAvailable` should be on the else end of the `task ? <Button> : null` ternary instead of null, right? Currently you get both the "Analysis details" button and then "not available" text below it.

**Review by mturley — CHANGES_REQUESTED** [review]

File: client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx (hunk 1 above)
Comment (ibolton336) [reply client/src/app/pages/applications/components/application-detail-drawer/application-detail-drawer-analysis.tsx:164]: Yeah - I was wondering what we should show in this case for the "catch all status". I think your suggestion makes sense.
