### PR TITLE
Tests: Add identity form tests

### LINKED ISSUE #338: Copy and paste ssh public key does not work for creating an identity
image

### LINKED ISSUE #339: Copy and paste does not work for creating a maven settings identity
image

### PR DESCRIPTION
**Pull request by ibolton336**
Add tests for identity form loading and form validation
Closes #338 
Closes #339

### CODE REVIEW

File: pkg/client/src/app/pages/identities/components/identity-form/identity-form.tsx [hunk 1]
```diff
@@ -36,18 +36,19 @@ import {
 } from "@app/queries/identities";
 import KeyDisplayToggle from "@app/common/KeyDisplayToggle";
 
-const xmllint = require("xmllint");
 const { XMLValidator } = require("fast-xml-parser");
 export interface IdentityFormProps {
   identity?: Identity;
   onSaved: (response: AxiosResponse<Identity>) => void;
   onCancel: () => void;
+  xmlValidationFn?: (value, currentSchema) => any;
```
Comment (gildub) [inline pkg/client/src/app/pages/identities/components/identity-form/identity-form.tsx:44]: Please lets avoid having technical implementation details as part of the name.
Could we please replace `xmlValidationFn` with `xmlValidator` or equivalent ?

File: pkg/client/src/app/pages/identities/components/identity-form/validateXML.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+const { xmllint } = require("xmllint");
+
+export const validateXML = (value, currentSchema) => {
```
Comment (gildub) [inline pkg/client/src/app/pages/identities/components/identity-form/validateXML.ts:3]: `values` and `currentSchema` need to by typed, seems they are always strings anyway.

**Review by gildub — CHANGES_REQUESTED** [review]
Looks good, just a couple of things with type and a function name.

**Review by gildub — APPROVED** [review]
LGTM
