### PR TITLE
:ghost: Improve status for migration waves

### LINKED ISSUE #964: When a ticket has failed, migration wave status does not reflect it.

### PR DESCRIPTION
**Pull request by ibolton336**
- Currently migration status is clickable/hoverable when the value is null / applications assigned to wave are empty. This fixes that. Closes https://github.com/konveyor/tackle2-ui/issues/961 

- Fixes No Issues status being "clickable / expandable" when no data is available in the table / migration wave 
- Remove impure functions deriving state & introduce a selector pattern. Usage is MigrationWaveWithStatus which includes ticket status & derived migration wave status on the  UI wave resource. Also, this moves away from prop drilling and moves all derived state to selectors for migration waves page and child component tables. Closes https://github.com/konveyor/tackle2-ui/issues/963 
- Surface error to aggregate migration wave status Closes #964 
- Refactor createTicket -> createTickets to allow for better handling of async code. This allows batch tickets to be created using Promise.all. #965 
- Add a constraint for ticket export. Prevents export of an application that is already assigned to a ticket. Partially addresses https://github.com/konveyor/tackle2-ui/issues/952

### CODE REVIEW

**Review by mturley — APPROVED** [review]

**Review by gildub — CHANGES_REQUESTED** [review]

File: client/src/app/utils/waves-selector.ts [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+
+  const applications =
+    queryClient.getQueryData<Application[]>([ApplicationsQueryKey]) || [];
+
+  const aggregatedTicketStatus = (
+    wave: MigrationWave,
+    tickets: Ticket[]
+  ): AggregateTicketStatus => {
+    const statuses = getTicketStatus(wave, tickets);
+    // const ticketStatusToAggregate: Map<TicketStatus, AggregateTicketStatus> =
```
Comment (gildub) [inline client/src/app/utils/waves-selector.ts:35]: Do we need to keep this ?

File: client/src/app/api/models.ts [hunk 2]
```diff
@@ -604,17 +608,26 @@ export type AggregateTicketStatus =
   | "In Progress"
   | "Completed"
   | "Error"
-  | "No Issues";
+  | "No Issues"
+  | "Not Started";
```
Comment (gildub) [inline client/src/app/api/models.ts:612]: Not sure where that one comes from.
I can't see that in the requirements.
I seems redundant with "Issues created"

**Review by gildub — COMMENTED** [review]
I haven't finished the review but getting there.

File: client/src/app/api/models.ts (hunk 2 above)
Comment (ibolton336) [reply client/src/app/api/models.ts:612]: image
Grabbed it from the enhancement

Comment (ibolton336) [reply client/src/app/api/models.ts:612]: https://github.com/konveyor/enhancements/tree/master/enhancements/tackle/tackle-jira-integration

File: client/src/app/pages/migration-waves/migration-waves.tsx [hunk 3]
```diff
@@ -543,36 +423,53 @@ export const MigrationWaves: React.FC = () => {
...
+                                              "terms.applications"
+                                            ).toLowerCase(),
+                                          })}
+                                        </DropdownItem>
+                                      </ConditionalTooltip>,
+                                      <ConditionalTooltip
+                                        isTooltipEnabled={
+                                          !!matchingConfictingApplication
+                                        }
+                                        content={`Application ${matchingConfictingApplication?.application?.id} has already been exported. Select a different application and try again. `}
```
Comment (gildub) [inline client/src/app/pages/migration-waves/migration-waves.tsx:454]: This seems not needed per related issue#952

File: client/src/app/queries/migration-waves.ts [hunk 4]
```diff
@@ -27,11 +29,14 @@ export const useCreateMigrationWaveMutation = (
...
 
 export const useFetchMigrationWaves = () => {
+  const queryClient = useQueryClient();
   const { isLoading, error, refetch, data } = useQuery({
     queryKey: [MigrationWavesQueryKey],
     queryFn: getMigrationWaves,
     refetchInterval: 5000,
     onError: (error) => console.log("error, ", error),
+    onSuccess: () => queryClient.invalidateQueries([TicketsQueryKey]),
+    select: (waves) => getWavesWithStatus(queryClient, waves),
```
Comment (gildub) [inline client/src/app/queries/migration-waves.ts:39]: To avoid systematically fetching all status data can't we create a separate fetch query ?
This will avoid to overload migrationwave data with the status data when only the migration data itself is only needed.

Comment (ibolton336) [reply client/src/app/queries/migration-waves.ts:39]: Not sure that we use the waves anywhere else? Maybe if we see a performance issue we could address this.

**Review by gildub — APPROVED** [review]
LGTM

**Review by gildub — APPROVED** [review]
