### PR TITLE
:bug: Fix Invalid questionnaire import bug

### LINKED ISSUE #3115: [BUG] Importing invalid questionnaire shows wrong notification
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

upstream

### Priority

Minor

### Current Behavior

When importing an invalid questionnaire, it shows a popup with the message:
Request failed with status code 400

Steps to Reproduce:

    Navigate to Assessment questionnaires page
    Click on import questionnaire ( invalid file attached )
    Select an invalid questionnaire

Expected results

A proper notification should be displayed indicating the questionnaire is invalid e.g.
Error:Field validation

More Info : https://issues.redhat.com/browse/MTA-2782

### Expected Behavior

_No response_

### How Reproducible

Always (Default)

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sshveta**
Resolves https://github.com/konveyor/tackle2-ui/issues/3115

After fix : 

image

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error messaging when questionnaire import fails with invalid data. Users will now see a clear "Invalid questionnaire imported" message instead of a generic error.

* **Documentation**
  * Added English translation for questionnaire import error message.

### CODE REVIEW

File: client/src/app/pages/assessment-management/import-questionnaire-form/import-questionnaire-form.tsx [hunk 1]
```diff
@@ -108,8 +108,14 @@ export const ImportQuestionnaireForm: React.FC<
   };
 
   const onHandleFailedQuestionnaireCreation = (error: AxiosError) => {
+    let errorMessage = getAxiosErrorMessage(error);
+
+    if (error.response?.status === 400) {
```
Comment (rszwajko) [inline client/src/app/pages/assessment-management/import-questionnaire-form/import-questionnaire-form.tsx:113]: why we use here a hardcoded message if the actual message returned is more specific? 
i.e. for the attached data:
```
{
    "error": "json: cannot unmarshal string into Go struct field Thresholds.thresholds.red of type uint"
}
```

**Review by rszwajko — APPROVED** [review]
Looks good!
